### ISSUE TITLE
Smooth out separation between NDT backend and frontend

### ISSUE THREAD

**Issue by mtlynch** [m-lab/website#102]
We'd like to make it as easy as possible for third parties to:
- take an M-Lab produced NDT widget and tweak it
- create their own NDT widget from scratch without forking the [NDT client](https://github.com/ndt-project/ndt/blob/master/HTML5-frontend/ndt-browser-client.js)

To do this, we have to solve the following problems:
- Implementers currently have to import [five different scripts](https://github.com/m-lab/m-lab.github.io/pull/76/files#diff-56ff23ff6448049981daee3c0344f9cdR22) to use the NDT backend. We should reduce this to just one script import, maybe with a minified script option.
- At least two of the five are UI libraries that the implementer shouldn't have to deal with if they're implementing their own UI (jQuery and gauge)
- Implementers currently have to set two global JS variables ([`CANV_GAUGE_FONTS_PATH`](https://github.com/m-lab/m-lab.github.io/pull/76/files#diff-56ff23ff6448049981daee3c0344f9cdR20) and [`ndtServer`](https://github.com/m-lab/m-lab.github.io/pull/76/files#diff-56ff23ff6448049981daee3c0344f9cdR31)). We should figure out another way of passing this information to NDT explicitly so that it's hard to omit accidentally and it doesn't clutter the global namespace.

If any of these changes require patches to https://github.com/ndt-project/ndt, we can submit a PR to them.

**Comment by critzo** [comment]
Reviewing and updating old tickets. This issue ought to be revisited after the planned review of and refactor of a unified NDT JavaScript client.

**Comment by critzo** [comment]
@jheretic this is related to what you're working on now.

**Comment by critzo** [comment]
With work proceeding on reference ndt7 clients, this issue will be superceded. Closing.
