### ISSUE TITLE
Printing the website removes most of the images?

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/website#152]
Any ideas on how this is happening?

![home - m-lab](https://cloud.githubusercontent.com/assets/941210/14300038/deec9416-fb5b-11e5-941c-d7908a833451.png)

cc @shredtechular @critzo

**Comment by shredtechular** [comment]
@georgiamoon That's a good catch...always forget about that use case!  

Typically a website should have a separate print.css file that browsers use to send format of a page to the printer in a nicely formatted fashion.  I don't see a print.css in the legacy website code in github?  

We can work on a stylesheet that cleans up the printed version of the page.  I don't think we want a lot of areas being printed though right?  Like the nav menus of all kinds (main, subnav, ToC, footer, etc...), video area on homepage, slider on homepage, and maybe some others I'm not thinking of.  I don't think someone looking to print out a page would want any of that stuff, right?  They just want the straight content and maybe a toned down header/footer whose only purpose is to show the beginning/end of the content and identify MLabs on it.

**Comment by georgiamoon** [comment]
So in this instance I was trying to print screen the site itself, so I did
want all of the images and wanted the website to print as is.

I think that the behavior you are describing makes sense for any of the
resource pages (e.g. data documentation, FAQs, blog posts, test pages,
etc), the except might be the home page itself, the observatory and the
visualization pages, where we want the graphics/images/text to print as is,
but fitting in the printable area.

Does that make sense?
