### ISSUE TITLE
Build check: Forbid "http://measurementlab.net"

### ISSUE THREAD

**Issue by mtlynch** [m-lab/website#166]
We should add a build check that checks Jekyll files for the strings `http://measurementlab.net` or `http://www.measurementlab.net` and flags the user to convert these to `{{ site.baseurl }}`

**Comment by critzo** [comment]
Adding this will require writing a custom rule in Ruby for the linter to use. 
https://github.com/markdownlint/markdownlint/blob/master/docs/creating_rules.md

The new rule can be saved in `.linter` and can then get added to `_tests/travis-checks`

**Comment by georgiamoon** [comment]
Is this still an issue @critzo ?

**Comment by critzo** [comment]
Yes. To do this we will need to write a custom linter rule in Ruby. My last comment points to the documentation on creating rules, which has not been done in this case. The non-technical solution here is to just check for this manually, which has worked well so far.

**Comment by apjanke** [comment]
Here's a PR to add the custom linter rule: https://github.com/m-lab/m-lab.github.io/pull/441

**Comment by critzo** [comment]
Actually I'm wrong. Links to internal site pages should not use the full URL, but instead use the Liquid variable `{{ site.baseurl }}`. For example `[link text]({{ site.baseurl }}/path/file.pdf)`. The site hosting now has redirects so all pages redirect to `https://www.measurementlab.net/<pagerequest>` so this should no longer be needed.
