### ISSUE TITLE
determine a strategy for internationalization

### ISSUE THREAD

**Issue by critzo** [m-lab/website#167]
We have an international audience, so our site should support translations into different languages. There are multiple ways to do this in Jekyll. We should identify which strategy we want to use and implement that.

**Comment by critzo** [comment]
This jekyll plugin looks like it would work well for providing internationalization support on the M-Lab website, but would require us to host somewhere other than Github:

https://github.com/Stonelinks/jekyll-gettext-plugin

If we wanted to try it we could host a copy of the site on Linode or elsewhere to test.

@m-lab/m-lab-developers let's discuss.

**Comment by georgiamoon** [comment]
Talked to Localization Lab today, and we should look at Lektor for this
