### ISSUE TITLE
NDT test at /tools/ndt may not work on IE11 (on Windows 7?)

### ISSUE THREAD

**Issue by nkinkade** [m-lab/website#208]
A person wrote in to support@measurementlab.net to stay that the NDT test on the M-Lab website was not functioning on his Windows 7 install in any of Chrome, Firefox and IE. Using our Windows 7 testbed client I was able to run tests using Firefox and Chrome, but IE11 fails ([seemingly somewhere in the getScriptPath() function](https://github.com/m-lab/ndt/blob/master/HTML5-frontend/script.js#L660)). It's not clear whether this is purely an IE11 issue, something specific to the testbed client, etc.  Perhaps someone else can test this on a few other machines?

**Comment by critzo** [comment]
@critzo will test this on a windows machine
