### ISSUE TITLE
update/add information around partners and support

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/website#239]
We should list more of the partners and supporting orgs / community members on the website

**Comment by georgiamoon** [comment]
Add MeasurementKit to the M-Lab website and perhaps a page about client integrations and recommendations

**Comment by critzo** [comment]
Compiling a list to start with:
- Mozilla
- SNV
- CIRA
- ?

**Comment by critzo** [comment]
@georgiamoon is this an update for the "[supporting partners](https://www.measurementlab.net/who/#supporting-partners)" ?

**Comment by nkinkade** [comment]
We should also probably remove or update a few partners:

* AQL - they don't respond to us, the site is in disrepair, and likely to be retired soon.
* CATNIX - the BKK01 site they hosted is gone.
* Cynet - they don't respond to us, the site is in disrepair, and likely to be retired soon.
* Vocus - the icon should be changed to INAP.
