### ISSUE TITLE
FAQ update: why are m-lab results different from other speed tests

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/website#373]
Since enabling IPv6 globally, there is a new dimension along which M-Lab may differ from other speed tests. And, from the same client, v4 and v6 performance may vary dramatically. The FAQ about what to expect from our speed test should mention this potential difference.

https://www.measurementlab.net/faq/#why-are-my-m-lab-results-different-from-other-speed-tests

**Comment by georgiamoon** [comment]
@stephen-soltesz can you (or would you recommend who on the team) draft some language to explain it?

**Comment by critzo** [comment]
@stephen-soltesz could you describe how measurements might vary if a client is using v4 versus v6?

**Comment by stephen-soltesz** [comment]
IPv4 and IPv6 routes may take different physical paths. Some IPv6 routes may be tunneled through IPv4, from the client e.g. https://tunnelbroker.net/ or at any point after the client depending on local network management.

Actually - do any of our clients have a way of explicitly specifying v4 or v6? for example, at speed.measurementlab.net?
