### ISSUE TITLE
Site hosting application does not reference our 10Gbps preferences

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/website#395]
My understanding is that we would prefer to deploy new sites with 10Gbps equipment and connectivity. However, our site hosting application and example setup guide do not reference our 10Gbps preference or support. https://www.measurementlab.net/contribute/#host-or-sponsor-an-m-lab-measurement-site

It would be helpful if the language there expressed highest preference for 10Gbps connectivity and that we would only consider 1Gbps under circumstances where this would not be a limiting factor.

**Comment by critzo** [comment]
@stephen-soltesz I've made some small updates to the form itself to include our preference for 10Gbps, and now am reviewing [this doc](https://docs.google.com/document/d/1qwp3V7gJVH-KGkxOyQwqE-AgDirexPO6WhBCqAk1aW4/edit#heading=h.qrn5qs8u1wrm) to ensure it's up to date and will then replace the current PDF on the website. Please feel free to comment in the doc if you would like. Thanks!

**Comment by critzo** [comment]
This is much clearer now on the contribute page, and we've dropped the google form (for now), so closing this issue.
