### ISSUE TITLE
note m-lab monitoring IPs to exclude when querying something other than release views

### ISSUE THREAD

**Issue by critzo** [m-lab/website#400]
If users query our release views, tests from our monitoring infrastructure are filtered out. However, users who may be querying base_tables should exclude them explicitly. This needs to be updated in our data docs.
Relates to https://github.com/m-lab/etl-schema/issues/6

45.56.98.222
2600:3c03::f03c:91ff:fe33:819
35.193.254.117
35.225.75.192
35.192.37.249

**Comment by georgiamoon** [comment]
I wonder if we should really just do this earlier in the ETL pipeline? Rather than having users potentially stumble on it? cc @gfr10598

**Comment by critzo** [comment]
OA&M addresses are now excluded from unified views. Closing.
