### ISSUE TITLE
Blog post about 2018 Internet Measurement Conference

### ISSUE THREAD

**Issue by critzo** [m-lab/website#422]

**Comment by critzo** [comment]
@georgiamoon if you have notes about this event, I can draft a post about it. @gfr10598 doesn't have cycles for this at the moment, but I can edit it.

**Comment by georgiamoon** [comment]
it's on my list. I should be able to get to it in the next few weeks.

**Comment by critzo** [comment]
@gfr10598 @georgiamoon If you have notes on this event, I can draft a blog post for you to review.
