### ISSUE TITLE
"Run reverse traceroute" link is broken

### ISSUE THREAD

**Issue by apjanke** [m-lab/website#444]
In the reverse traceroute test page, it links to what looks like a live page to run reverse traceroute.

```
[Run Reverse Traceroute](http://revtr.cs.washington.edu/)
```

That page is currently broken. It's redirecting to a default "your Apache server is working" page.

This is causing the locally-run (non-`--quick`) Travis checks to fail.

```
[~/local/repos/m-lab.github.io]
$ ./_tests/travis-checks                                                     master ✱
[...]

Checking 358 external links...
Ran on 166 files!


- ./_site/tests/reverse_traceroute/index.html
  *  External link http://revtr.cs.washington.edu/ failed: 403 No error
htmlproofer 3.0.5 | Error:  HTML-Proofer found 1 failure!
```

Probably need to contact someone who runs https://research.cs.washington.edu/networking/astronomy/reverse-traceroute.html and see if they can get it working again. (The "comments to arvind" contact link on that page is 404, so I'm not sure how to do that.)

**Comment by apjanke** [comment]
I googled and found an email for Arvind Krishnaumurthy, who I think is the "arvind" mentioned on that page, and sent him an email asking him about the issue.

**Comment by critzo** [comment]
Resolved in a recent commit while moving the site hosting.
