### ISSUE TITLE
Update Best Practices test rate recommendations

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/website#471]
Currently, the best practices recommend "automatic and/or bandwidth intensive tests should not initiate more than two tests per hour to a server."

https://www.measurementlab.net/develop/#best-practices-on-test-scheduling-and-frequency

Our rate limiting logic (not active) uses a threshold of 40 tests per day.

**Comment by pboothe** [comment]
Want to distinguish integrations and individual testing.

Individuals can feel free to test more frequently (up to 40 times per day), but integrations should restrict themselves to no more than 4 times per day.

**Comment by stephen-soltesz** [comment]
I suggest describing the difference as: batch scheduling and interactive scheduling. A single integration could have both modes.
