### ISSUE TITLE
NDT client test in website needs c2s fix

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/website#507]
The c2s client javascript client fix from https://github.com/m-lab/ndt-server/pull/172 should be included in the website client also.

<img width="1136" alt="Screen Shot 2019-08-28 at 10 07 47 AM" src="https://user-images.githubusercontent.com/1085316/63863227-d9939900-c97b-11e9-879d-506fa66b7761.png">

**Comment by critzo** [comment]
Perhaps this issue should be to update the website client with the one in ndt-server?

**Comment by pboothe** [comment]
Website submodule has been updated, but this did not fix the problem.

**Comment by pboothe** [comment]
Long term (2 months?) plan is to use the NDT7 test instead.

**Comment by critzo** [comment]
Recent changes to the NDT pages also have removed the test from the /tests/ndt landing page. The issue with the current client can be debugged by viewing this page: https://www.measurementlab.net/p/ndt-ws.html

**Comment by critzo** [comment]
Until we're ready to migrate the test on the website to NDT7, we've redirected users to speed.measurementlab.net per #513
