### ISSUE TITLE
Update description of ndt7 to mention cleartext tests

### ISSUE THREAD

**Issue by robertodauria** [m-lab/website#534]
At https://www.measurementlab.net/tests/ndt/ we state "ndt7 is a new NDT protocol that operates solely over TLS port 443", which won't be true anymore after https://github.com/m-lab/ndt-server/pull/222 is merged.

I'm opening this issue as a reminder to update it.

@critzo are you aware of any other place on the website that should be updated after that change?

**Comment by critzo** [comment]
Blocked by #545
