### ISSUE TITLE
Support Partners and Supporting Research Projects out of date

### ISSUE THREAD

**Issue by nkinkade** [m-lab/website#568]
I happened to be looking over the `/who` page and noticed that the both the **Supporting Research Partners** and **Supporting Partners** sections are very out of date.

I believe all of these supporting partners should be removed:

- AQL
- CYNET
- OCECPR
- GIX
- ISC
- Internap
- Planet Lab
- Sam Knows

Virtually all of the supporting research partners should be removed or are out of date.

**Comment by critzo** [comment]
@nkinkade I'll remove those supporting partners who don't have any current connection to M-Lab. Of the list that you sent, ISC still hosts nuq02, but others will be removed. All of the others that remain either host a singleton site, give us money, or have an integration. So really there aren't very many that need to be removed.

**Comment by critzo** [comment]
I see you meant the other list @nkinkade - you're right- the list of "supporting research partners" needs an update.

**Comment by nkinkade** [comment]
Ah, good catch on ISC. I forgot about NUQ02. Making that list of "singleton" sites really reminded me that there actually are far more supporting site hosts that had been thinking, with ISC as one of them, which I missed in my list, I believe.
