### ISSUE TITLE
Add recent presentations

### ISSUE THREAD

**Issue by critzo** [m-lab/website#578]
* [20200605 - Peter Boothe - NDT, its evolution, and how you can now easily run your own server](https://www.youtube.com/watch?v=mf65RLIPYmE&feature=youtu.be)
* [20200615 - Lai Yi Ohlsen - M-Lab: Measuring Internet Performance](https://www.youtube.com/watch?v=oRtvj4v0EeE)

@pboothe  @laiyi-ohlsen I'll also include your slides. If you have the links to those handy and want to add a comment here to them, that would be helpful.

**Comment by laiyi-ohlsen** [comment]
Thanks @critzo ! https://bit.ly/2UKTIrm. As an FYI, they've asked me to re record it because my audio was off in the beginning. I'll let you know when there's an updated link.

**Comment by critzo** [comment]
super! thanks @laiyi-ohlsen !

**Comment by pboothe** [comment]
https://drive.google.com/corp/drive/folders/1abrZ0T8-_Rrlu6SQKOQx2Ku6sFwmccHA is my ES.net brownbag slides

**Comment by critzo** [comment]
thanks @pboothe
