### ISSUE TITLE
Announce Wehe integration on M-Lab

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/website#624]
Arcep announced the integration with wehe recently -- https://www.arcep.fr/actualites/les-communiques-de-presse/detail/n/internet-ouvert-211220.html

We should publish a blog post of our own.

**Comment by critzo** [comment]
@laiyi-ohlsen Started a [draft doc](https://docs.google.com/document/d/1uib6piiXpG1_cecht1s5IaUquvmXEYo_tvW3UereiuM/edit).

**Comment by critzo** [comment]
Completed in #630
