### ISSUE TITLE
Deploy universal Geo2 annotation in unified views

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/website#692]
- [ ] Deploy website with announcement https://github.com/m-lab/website/pull/691
- [ ] Send message to discuss@ citing change
- [ ] Deploy etl-schema with https://github.com/m-lab/etl-schema/pull/123

**Comment by laiyi-ohlsen** [comment]
I'd put in this order: 

- [ ] Deploy etl-schema with https://github.com/m-lab/etl-schema/pull/123
- [ ] Deploy website with announcement https://github.com/m-lab/website/pull/691
- [ ] Send message to discuss@ citing change

But other than that lgtm.

**Comment by stephen-soltesz** [comment]
Completed incidentally as part of https://github.com/m-lab/etl-schema/issues/129
