### ISSUE TITLE
Handle non-www to www redirection better

### ISSUE THREAD

**Issue by nkinkade** [m-lab/website#97]
We serve the M-Lab site on www.measurementlab.net, and we want to redirect requests for measurementlab.net to that domain. However, we need to point the root domain to an IP address (an A record).  CloudFront and S3 don't give you IP addresses to point to (that I know of), but simply domain names, and they manage and muck the underlying IP addresses as they need to. A lot of DNS hosting services provide a redirection service like this, include Amazon's own Route 53.  Since we host our own DNS for measurementlab.net, we're going to need to figure out how to redirect requests to measurementlab.net to www.measurementlab.net.  As a stop-gap, I pointed measurementlab.net to our Linode Nagios VM, and Apache on that machine redirects (301) all requests to www.measurementlab.net. While this works fine, we won't ultimately want the Linode VM having anything to do with the core website. We can find some service will provide this redirection for us, or we could deploy the redirection on some other server we manage, or we could move our DNS to another provider (like Google Cloud DNS or Amazon Route 53) who provides this sort of redirect.

Additionally the above temporary redirection mechanism does not work for HTTPS at the moment.

**Comment by critzo** [comment]
In https://github.com/m-lab/ops-tracker/issues/145  and https://github.com/m-lab/m-lab.github.io/issues/268
I've changed the behavior of our [CloudFront entry](https://console.aws.amazon.com/cloudfront/home?region=us-east-1#distribution-settings:EDI2Q8DF7TZ0I) to redirect HTTP to HTTPS. So this issue is largely resolved for now. As mentioned in those other tickets, https without www does not yet redirect, but we should do this in Amazon instead of using EB for redirects.

**Comment by nkinkade** [comment]
I'm reopening this issue because I believe the root problem still exists: host measurementlab.net point to the IP of eb.measurementlab.net, and EB is the one redirecting those bare requests to www.measurementlab.net. We definitely want to get EB out of this DNS loop.

The HTTPS redirection bit was resolved by getting a certbot client running on EB, so that part is done, but we still need to get EB out of the loop.

**Comment by critzo** [comment]
With the move to Firebase, this is now resolved. All redirects are handled in Firebase configs.
